### ISSUE TITLE
Что-то не работает....

### ISSUE THREAD

**Issue by shauru1118** [ThisIsHyum/lms_calculator#2]
![Снимок экрана 2024-12-24 102208](https://github.com/user-attachments/assets/079cc7a7-b2b1-4c24-85cd-ea74563d4956)

скопировал в одну строку, все как в readme, но все равно ошибки

**Comment by ThisIsHyum** [comment]
Оно должно быть не в одну строку. Либо убрать все "\", либо перенести в новую строку строки после "\"
